/**
 * Currency Utilities
 * Reusable currency conversion and formatting functions
 */

export interface ExchangeRate {
  from: string;
  to: string;
  rate: number;
  numerator?: number | null;
  denominator?: number | null;
  isAutoGenerated?: boolean;
}

export const CURRENCIES = [
  { value: "EUR", label: "EUR - Euro", symbol: "€" },
  { value: "USD", label: "USD - US Dollar", symbol: "$" },
  { value: "GBP", label: "GBP - British Pound", symbol: "£" },
  { value: "CAD", label: "CAD - Canadian Dollar", symbol: "C$" },
  { value: "DZD", label: "DZD - Algerian Dinar", symbol: "DZD" },
];

export const CURRENCY_SYMBOLS: Record<string, string> = {
  EUR: "€",
  USD: "$",
  GBP: "£",
  CAD: "C$",
  DZD: "DZD",
};

/**
 * Get currency symbol for a given currency code
 * @param currency - Currency code (e.g., "EUR", "USD")
 * @returns Currency symbol or empty string if not found
 */
export const getCurrencySymbol = (currency: string): string => {
  return CURRENCY_SYMBOLS[currency] || "";
};

/**
 * Convert price from one currency to another using exchange rates
 * Uses numerator/denominator for higher precision when available
 * Falls back to decimal rate if numerator/denominator not provided
 *
 * @param price - Price to convert (null/undefined returned as-is)
 * @param fromCurrency - Source currency code
 * @param toCurrency - Target currency code
 * @param exchangeRates - Array of exchange rates to use for conversion
 * @returns Converted price, or original price if conversion not needed/possible
 */
export const convertPrice = (
  price: number | null | undefined,
  fromCurrency: string,
  toCurrency: string,
  exchangeRates: ExchangeRate[]
): number | null | undefined => {
  // Guard: only convert when price is not null/undefined
  if (fromCurrency === toCurrency || price == null) return price;

  // Find the exchange rate for this currency pair
  const rate = exchangeRates.find((r) => r.from === fromCurrency && r.to === toCurrency);

  // If no rate found, return original price
  if (!rate) return price;

  // Calculate using numerator/denominator if available (more precise)
  if (rate.numerator !== undefined && rate.denominator !== undefined) {
    return price * (rate.numerator! / rate.denominator!);
  }

  // Fall back to decimal rate
  return rate.rate ? price * rate.rate : price;
};

/**
 * Format price with thousand separators and 2 decimal places
 * @param price - Price to format (null/undefined returned as-is)
 * @param currency - Currency code for proper formatting
 * @returns Formatted price string with thousand separators and 2 decimals (e.g., "19,500,000.00")
 */
export const formatPrice = (price: number | null | undefined, currency: string = "EUR"): string => {
  if (price == null || price === undefined) return "";

  try {
    // Use Intl.NumberFormat for proper locale-aware formatting
    // For DZD, use French locale (common in Algeria)
    // For other currencies, use en-US or appropriate locale
    const locale = currency === "DZD" ? "fr-FR" : "en-US";

    return new Intl.NumberFormat(locale, {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }).format(price);
  } catch (error) {
    // Fallback to manual formatting if Intl fails
    return price.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  }
};

