
/**
 * Currency Exchange Rates API
 * Manage exchange rates for different currencies
 * Rates stored as fractions (numerator/denominator) for maximum precision
 */

import { NextRequest, NextResponse } from 'next/server';
import { writeFile, readFile } from 'fs/promises';
import { join } from 'path';

// Path to store exchange rates
const RATES_FILE = join(process.cwd(), 'db', 'exchange-rates.json');

interface ExchangeRate {
  from: string;
  to: string;
  numerator: number;      // Store as fraction for precision
  denominator: number;
  updatedAt: string;
  isAutoGenerated?: boolean;
}

// Default exchange rates (stored as fractions)
const DEFAULT_RATES: ExchangeRate[] = [
  { from: 'EUR', to: 'USD', numerator: 27, denominator: 25, rate: 1.08, updatedAt: new Date().toISOString() },
  { from: 'EUR', to: 'GBP', numerator: 43, denominator: 50, rate: 0.86, updatedAt: new Date().toISOString() },
  { from: 'EUR', to: 'CAD', numerator: 147, denominator: 100, rate: 1.47, updatedAt: new Date().toISOString() },
  { from: 'USD', to: 'EUR', numerator: 93, denominator: 100, rate: 0.93, updatedAt: new Date().toISOString() },
  { from: 'GBP', to: 'EUR', numerator: 29, denominator: 25, rate: 1.16, updatedAt: new Date().toISOString() },
  { from: 'CAD', to: 'EUR', numerator: 34, denominator: 50, rate: 0.68, updatedAt: new Date().toISOString() },
  { from: 'EUR', to: 'DZD', numerator: 1, denominator: 270, rate: 0.0037037037037037, updatedAt: new Date().toISOString() },
  { from: 'USD', to: 'DZD', numerator: 80, denominator: 1, rate: 80, updatedAt: new Date().toISOString() },
];

// Helper function to calculate decimal rate from fraction
const getDecimalRate = (numerator: number, denominator: number): number => {
  return denominator !== 0 ? numerator / denominator : 0;
};

async function loadRates(): Promise<ExchangeRate[]> {
  try {
    const data = await readFile(RATES_FILE, 'utf-8');
    return JSON.parse(data);
  } catch {
    return DEFAULT_RATES;
  }
}

async function saveRates(rates: ExchangeRate[]): Promise<void> {
  await writeFile(RATES_FILE, JSON.stringify(rates, null, 2), 'utf-8');
}

/**
 * GET /api/exchange-rates
 * Get all exchange rates
 */
export async function GET() {
  try {
    const rates = await loadRates();
    return NextResponse.json(rates);
  } catch (error: any) {
    console.error('Error fetching exchange rates:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to fetch exchange rates' },
      { status: 500 }
    );
  }
}

/**
 * POST /api/exchange-rates
 * Add or update an exchange rate
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();

    if (!body.from || !body.to || (body.numerator === undefined && body.denominator === undefined)) {
      return NextResponse.json(
        { error: 'from, to, and numerator/denominator are required' },
        { status: 400 }
      );
    }

    const rates = await loadRates();

    // Find existing rate and update, or add new
    const existingIndex = rates.findIndex(
      (r) => r.from === body.from && r.to === body.to
    );

    const numerator = body.numerator!;
    const denominator = body.denominator!;
    const rate = getDecimalRate(numerator, denominator);

    if (existingIndex >= 0) {
      // Update existing rate
      rates[existingIndex] = {
        ...rates[existingIndex],
        numerator: numerator,
        denominator: denominator,
        rate: rate,
        updatedAt: new Date().toISOString(),
      };
    } else {
      // Add new rate
      rates.push({
        from: body.from,
        to: body.to,
        numerator: numerator,
        denominator: denominator,
        rate: rate,
        updatedAt: new Date().toISOString(),
      });

      // Automatically add reverse pair
      const reverseFrom = body.to;
      const reverseTo = body.from;
      const reverseNumerator = denominator;
      const reverseDenominator = numerator;
      const reverseRate = rate !== 0 ? denominator / numerator : 0;

      // Check if reverse rate already exists
      const reverseExistingIndex = rates.findIndex(
        (r) => r.from === reverseFrom && r.to === reverseTo
      );

      if (reverseExistingIndex >= 0) {
        // Update existing reverse rate
        rates[reverseExistingIndex] = {
          ...rates[reverseExistingIndex],
          numerator: reverseNumerator,
          denominator: reverseDenominator,
          rate: reverseRate,
          updatedAt: new Date().toISOString(),
          isAutoGenerated: true,
        };
      } else {
        // Add new reverse rate
        rates.push({
          from: reverseFrom,
          to: reverseTo,
          numerator: reverseNumerator,
          denominator: reverseDenominator,
          rate: reverseRate,
          updatedAt: new Date().toISOString(),
          isAutoGenerated: true,
        });
      }
    }

    await saveRates(rates);

    return NextResponse.json({
      success: true,
      message: 'Exchange rate saved successfully',
      rate: rates.find((r) => r.from === body.from && r.to === body.to),
      addedReverseRate: rates.find((r) => r.from === body.to && r.to === body.from),
    });
  } catch (error: any) {
    console.error('Error saving exchange rate:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to save exchange rate' },
      { status: 500 }
    );
  }
}

/**
 * DELETE /api/exchange-rates
 * Delete an exchange rate
 */
export async function DELETE(request: NextRequest) {
  try {
    const url = new URL(request.url);
    const from = url.searchParams.get('from');
    const to = url.searchParams.get('to');

    if (!from || !to) {
      return NextResponse.json(
        { error: 'from and to query parameters are required' },
        { status: 400 }
      );
    }

    const rates = await loadRates();
    const filteredRates = rates.filter(
      (r) => r.from !== from || r.to !== to
    );

    await saveRates(filteredRates);

    return NextResponse.json({
      success: true,
      message: 'Exchange rate deleted successfully',
    });
  } catch (error: any) {
    console.error('Error deleting exchange rate:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to delete exchange rate' },
      { status: 500 }
    );
  }
}
