import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Check if configuration exists
  const existingConfig = await prisma.pDFConfiguration.findFirst();

  if (existingConfig) {
    console.log('Configuration already exists with ID:', existingConfig.id);
    console.log('Proforma Description Language:', existingConfig.proformaDescriptionLanguage);
    console.log('Proforma Terms Title:', existingConfig.proformaTermsTitle);
    console.log('Has proformaPaymentMethod:', !!existingConfig.proformaPaymentMethod);
    console.log('Has proformaDeliveryTimeValue:', !!existingConfig.proformaDeliveryTimeValue);
    console.log('Has proformaWarrantyValue:', !!existingConfig.proformaWarrantyValue);
  } else {
    console.log('No configuration found. Creating default configuration...');

    const newConfig = await prisma.pDFConfiguration.create({
      data: {
        descriptionLanguage: "FRENCH",
        useInInvoice: true,
        useInProforma: true,
        useInDeliveryNote: true,
        useInPurchaseOrder: true,
        useInNameplate: false,
        useInTechnicalFile: false,
        includeTelephone: false,
        includeFax: false,
        includeAddress: false,
        includeEmail: false,
        includeRcn: false,
        includeNif: false,
        includeNis: false,
        includeRib: false,
        includeBankName: false,
        includeCapitalSocial: false,
        leftPartDirection: "LTR",
        rightPartDirection: "RTL",
        headerLineSpacing: 1.0,
        companyNameFontFamily: "HELVETICA",
        companyNameFontSize: 24,
        companyNameTextColor: "#000000",
        companyNameLineSpacing: 1.0,
        descriptionFontFamily: "HELVETICA",
        descriptionFontSize: 12,
        descriptionTextColor: "#000000",
        descriptionLineSpacing: 1.0,
        logoScaling: 1.0,
        logoOffsetX: 0,
        logoOffsetY: 0,
        labelFontFamily: "HELVETICA",
        labelFontSize: 12,
        labelTextColor: "#000000",
        labelLineSpacing: 1.0,
        dataFontFamily: "HELVETICA",
        dataFontSize: 12,
        dataTextColor: "#000000",
        dataLineSpacing: 1.0,
        proformaTopBodyDirection: "LTR",
        proformaDescriptionLanguage: "ENGLISH",
        proformaTitlePosition: "center",
        proformaTitleFontFamily: "HELVETICA",
        proformaTitleFontSize: 16,
        proformaTitleTextColor: "#000000",
        proformaTitleLineSpacing: 1.0,
        proformaTitleLetterSpacing: 0.0,
        proformaTitleBold: true,
        proformaTitleUnderline: false,
        proformaClientInfoPosition: "left",
        proformaClientLabelText: "Client :",
        proformaClientFontFamily: "HELVETICA",
        proformaClientFontSize: 12,
        proformaClientTextColor: "#000000",
        proformaClientLineSpacing: 1.0,
        proformaClientLetterSpacing: 0.0,
        proformaClientBold: true,
        proformaClientUnderline: false,
        proformaDatePosition: "left",
        proformaLocationDateLabelText: "M'sila le",
        proformaDateFontFamily: "HELVETICA",
        proformaDateFontSize: 12,
        proformaDateTextColor: "#000000",
        proformaDateLineSpacing: 1.0,
        proformaDateLetterSpacing: 0.0,
        proformaDateBold: false,
        proformaDateUnderline: false,
        proformaTableTextAlignment: "left",
        proformaTableDirection: "LTR",
        proformaTableLabelFontFamily: "HELVETICA",
        proformaTableLabelFontSize: 11,
        proformaTableLabelTextColor: "#000000",
        proformaTableLabelLineSpacing: 1.0,
        proformaTableLabelLetterSpacing: 0.0,
        proformaTableLabelBold: true,
        proformaTableLabelUnderline: false,
        proformaTableValueFontFamily: "HELVETICA",
        proformaTableValueFontSize: 11,
        proformaTableValueTextColor: "#000000",
        proformaTableValueLineSpacing: 1.0,
        proformaTableValueLetterSpacing: 0.0,
        proformaTableValueBold: false,
        proformaTableValueUnderline: false,
        proformaEmptyRows: 8,
        proformaMaxItemsPerPage: 15,
        proformaTermsPosition: "left",
        proformaTermsTitle: "Modalités de paiement, livraison et garantie :",
        proformaTermsFontFamily: "HELVETICA",
        proformaTermsFontSize: 11,
        proformaTermsTextColor: "#000000",
        proformaTermsLineSpacing: 1.0,
        proformaTermsLetterSpacing: 0.0,
        proformaTermsBold: false,
        proformaTermsUnderline: false,
        // Proforma Terms & Conditions Settings
        proformaPaymentMethod: "full_payment",
        proformaDeliveryTimeValue: 3,
        proformaDeliveryTimeUnit: "months",
        proformaProformaValidityValue: 3,
        proformaProformaValidityUnit: "months",
        proformaWarrantyValue: 12,
        proformaWarrantyUnit: "months",
        proformaSignatureLeftLabelText: "Gérant",
        proformaSignatureRightLabelText: "Client",
        proformaPageNumberingText: "Page 1 sur 1",
        // Invoice Settings
        invoiceTopBodyDirection: "LTR",
        invoiceTitlePosition: "center",
        invoiceTitleFontFamily: "HELVETICA",
        invoiceTitleFontSize: 16,
        invoiceTitleTextColor: "#000000",
        invoiceTitleLineSpacing: 1.0,
        invoiceTitleLetterSpacing: 0.0,
        invoiceTitleBold: true,
        invoiceTitleUnderline: false,
        invoiceClientInfoPosition: "left",
        invoiceClientLabelText: "Client :",
        invoiceClientFontFamily: "HELVETICA",
        invoiceClientFontSize: 12,
        invoiceClientTextColor: "#000000",
        invoiceClientLineSpacing: 1.0,
        invoiceClientLetterSpacing: 0.0,
        invoiceClientBold: true,
        invoiceClientUnderline: false,
        invoiceDatePosition: "left",
        invoiceLocationDateLabelText: "M'sila le",
        invoiceDateFontFamily: "HELVETICA",
        invoiceDateFontSize: 12,
        invoiceDateTextColor: "#000000",
        invoiceDateLineSpacing: 1.0,
        invoiceDateLetterSpacing: 0.0,
        invoiceDateBold: false,
        invoiceDateUnderline: false,
        invoiceTableTextAlignment: "left",
        invoiceTableDirection: "LTR",
        invoiceTableLabelFontFamily: "HELVETICA",
        invoiceTableLabelFontSize: 11,
        invoiceTableLabelTextColor: "#000000",
        invoiceTableLabelLineSpacing: 1.0,
        invoiceTableLabelLetterSpacing: 0.0,
        invoiceTableLabelBold: true,
        invoiceTableLabelUnderline: false,
        invoiceTableValueFontFamily: "HELVETICA",
        invoiceTableValueFontSize: 11,
        invoiceTableValueTextColor: "#000000",
        invoiceTableValueLineSpacing: 1.0,
        invoiceTableValueLetterSpacing: 0.0,
        invoiceTableValueBold: false,
        invoiceTableValueUnderline: false,
        invoiceEmptyRows: 8,
        invoiceMaxItemsPerPage: 15,
        invoiceTermsPosition: "left",
        invoiceTermsTitle: "Modalités de paiement, livraison et garantie :",
        invoiceTermsFontFamily: "HELVETICA",
        invoiceTermsFontSize: 11,
        invoiceTermsTextColor: "#000000",
        invoiceTermsLineSpacing: 1.0,
        invoiceTermsLetterSpacing: 0.0,
        invoiceTermsBold: false,
        invoiceTermsUnderline: false,
        invoiceSignatureLeftLabelText: "Gérant",
        invoiceSignatureRightLabelText: "Client",
        invoicePageNumberingText: "Page 1 sur 1",
      },
    });

    console.log('Default configuration created with ID:', newConfig.id);
  }
}

main()
  .catch((e) => {
    console.error('Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
